/**
  * 파일명 : wijmo.js
  * 파일 기능 :
  * 작성자 : 정재은 외 3명
  * 최종 작성일 : 2021-02-16
  * License By Shinsegae I&C
  * 2021-02-16 Update: pdf 다운로드 입력중
 **/

import * as wjcCore from '@grapecity/wijmo'
// https://www.grapecity.com/wijmo/licensing - 라이선스에 대한 정보
import '@grapecity/wijmo.touch'
import '@grapecity/wijmo.grid.multirow'
import '@grapecity/wijmo.vue2.grid'
import '@grapecity/wijmo.vue2.grid.multirow'
// import '~@grapecity/styles/wijmo.css'
// import 'wijmo/wijmo.styles/wijmo.css'
import '@grapecity/wijmo.vue2.grid.filter'
// import { ODataCollectionView } from '@grapecity/wijmo.odata'
import '@grapecity/wijmo.vue2.chart'
import '@grapecity/wijmo.vue2.chart.animation'
import '@grapecity/wijmo.vue2.grid.search'
import '@grapecity/wijmo.vue2.input'
import '@grapecity/wijmo.vue2.gauge'
import '@grapecity/wijmo.vue2.core'

console.log(process.env.NODE_ENV)
if (process.env.NODE_ENV === 'production') {
  wjcCore.setLicenseKey('admin.chp-dev.spharos.com|admin.chp-prd.spharos.com|admin.cmp.spharos.com|admin.cmp-dev.spharos.com|chp.spharos.com|chp-dev.spharos.com|chp-prd.spharos.com|cmp.spharos.com|cmp-admin.spharos.com|cmp-dev.spharos.com,948493285278583#B0y4Hu8WatRWYiojIz5GRiwiIpgKlsTalsTbnsTYlsT8sqjLhsD0isjCIkqI1cG008er0iojIh94QiwiIzgTN8cjM5gjMzkDN8QTOiojIklkIs4nIxYHMyAjMiojIyVmdiwSZzxWYmpjIyNHZisnOiwmbBJye0ICRiwiI34TU5JFeSd5SoFETwpnZV9WYSNlSQR6ctpmeJJWUvZ6LwpkSudXQ4d6S7VWNuNzKGhlbWJTQOxmWyQGbRV5b9NlSjNUcJNGMaZEZphUWQx6M6QjV94WdXdVSn34ay86aslENHhzchNjU6c7QZx6bnhVOWZ4NCd7YOh4UIVVWH34akVHSjVWZm9WToxmc4c4MWdXTLBXNal5Q9QDU7t6RxJmZ8djRXhHT4gTZlZzVs3CSBNHNJ3GekN7c8BHTB3GNEh4Q7JUOJJjSyp7VwAzNDpVSKhmahtUNBB7bad4KzF5c9s6S6NGa6tyLM9Uek96ZvYDZpB5ZxsWMRhVchFjSLRXUatCdyUGUPp4KMljeDZ5Q4cldrNUbX9ma9E7Y7ITNY3mZ5pWNQpEMvM4M5BnNpVTOwVDT8ZGNyYFbxI5Y7xUTxNlMyQzbnFnQFBHWidTW9cUWWlEWrMmI0IyUiwiIyUjQEVjQ5IjI0ICSiwyM8YDMwIzNwETM0IicfJye&Qf35VfikEMyIlI0IyQiwiIu3Waz9WZ4hXRgACdlVGaThXZsZEIv5mapdlI0IiTisHL3JSNJ9UUiojIDJCLi86bpNnblRHeFBCIyV6dllmV4J7bwVmUg2Wbql6ViojIOJyes4nILdDOIJiOiMkIsIibvl6cuVGd8VEIgc7bSlGdsVXTg2Wbql6ViojIOJyes4nI4YkNEJiOiMkIsIibvl6cuVGd8VEIgAVQM3EIg2Wbql6ViojIOJyes4nIzMEMCJiOiMkIsISZy36Qg2Wbql6ViojIOJyes4nIVhzNBJiOiMkIsIibvl6cuVGd8VEIgQnchh6QsFWaj9WYulmRg2Wbql6ViojIOJyebpjIkJHUiwiIwAzN5cDMgMTMzAzMyAjMiojI4J7QiwiIt36YuM7byFGawNnL6VGZtAXbjxSbvNmLz3mchhGcz9ibp5GZh5CctNGLt36YuM7byFGawNnLw56Ys46bj9ycvJXYoB7cuQmcw5CcoNGLt36YuM7byFGawNnL6VGZtAHajxSbvNmLz3mchhGcz9CcoNGLt36YuM7byFGawNnL6VGZtAXbj9ibp5GZhxSbvNmLz3mchhGcz9CctNmLulWbkFGLt36YuM7byFGawNnLkJHctAHaj9ibp5GZhxSbvNmLz3mchhGcz9idllWrw')
} else {
  wjcCore.setLicenseKey('bnk-demo.spharoscmp.com|bnk-demo-admin.spharoscmp.com|demo.spharoscmp.com|demo-admin.spharoscmp.com|gs-demo.spharoscmp.com|gs-demo-admin.spharoscmp.com,948493285278583#B0QzHOuEyOoLyOKgQqiszZorj1tqLiOiEmTDJCLiMDO5gzNyUDOyMTO4gDN9IiOiQWSiwSfiEjdwIDMyIiOiIXZ6JCLlNHbhZmOiI7ckJye0ICbuFkI1pjIEJCLi4TPBhke4BjN8pEa9wkcKhkdLRWWKBDcl9kcrkDVwEFaZZHSyg5QZZnbGlTYKFnSwU7bNVXdGd7b9kTNPlDaBJVRTJkezczV9ZFduRHZ4pkSjhmcrk5QnpWdygTYUlWS4REcLdlMot6T0J7cJRDNyIDRG34aGxkUlpVNlplZTNWc7BzLWZ4N8FDSIB5VWtUeRZ7Sy4mb4o6ToNWQz3mcBBDWsREUihGWaZzSkVVMvhnQ4ZWWsVFbrFnb9M7cxZlYoBzb4wGaHNDctNjbLF4bUdjU8d7T09mYwFWcphjcDRkcThUUSpEOZBHT9UHeH5kexIjNpJVeyREcFtmUFhVT6k6a7QGVzYkTuRmQMN7RTlmN9wENIBDOE5UT5MUb6tkSuF5YxQzdQlFS85WcIBTNmV6SohzMsRkaSBjdmJ7K4VXY7czTxk4aPFnUk3CcxIkU9NHerkmbkVDaiojITJCLicjRzMDN6IUMiojIIJCL6UzN6MTOxgDO0IicfJye&Qf35VfikEMyIlI0IyQiwiIu3Waz9WZ4hXRgACdlVGaThXZsZEIv5mapdlI0IiTisHL3JSNJ9UUiojIDJCLi86bpNnblRHeFBCIyV6dllmV4J7bwVmUg2Wbql6ViojIOJyes4nILdDOIJiOiMkIsIibvl6cuVGd8VEIgc7bSlGdsVXTg2Wbql6ViojIOJyes4nI4YkNEJiOiMkIsIibvl6cuVGd8VEIgAVQM3EIg2Wbql6ViojIOJyes4nIzMEMCJiOiMkIsISZy36Qg2Wbql6ViojIOJyes4nIVhzNBJiOiMkIsIibvl6cuVGd8VEIgQnchh6QsFWaj9WYulmRg2Wbql6ViojIOJyebpjIkJHUiwiIxUTMzgDMgUTMyETMyAjMiojI4J7QiwiIt36YuAXbjN7byFGawNnLulWbkFWLv5WZk5ycnxSbvNmLw56Yz3mchhGcz9ybtVGZtM7Zs46bj9CctN6cvJXYoB7cu8WatRWYt2WblRGLt36YuAXbjN7byFGawNnLv5WZkxSbvNmLw56Yz3mchhGcz9ibp5GZh5ybtVGZtsmbixSbvNmLw56Yz3mchhGcz9ybtVGZtsmbiJiOiMXbEJCLikCqUyOpVyOtdyOYVHO')
}

export default wjcCore
